/* eslint-disable @typescript-eslint/no-unused-vars */
import { h3lp } from '../'

describe('string', () => {
	const context = JSON.parse('{}')
	test('capitalize', () => {
		expect(h3lp.string.capitalize('hello world')).toStrictEqual('Hello world')
		expect(h3lp.string.capitalize('house')).toStrictEqual('House')
	})
	test('initCap', () => {
		expect(h3lp.string.initCap('Lo peor que hacen los malos es obligarnos a dudar de los buenos')).toStrictEqual('Lo Peor Que Hacen Los Malos Es Obligarnos A Dudar De Los Buenos')
		expect(h3lp.string.initCap('El dinero no puede comprar la vida')).toStrictEqual('El Dinero No Puede Comprar La Vida')
		expect(h3lp.string.initCap('Los hermanos sean unidos porque ésa es la ley primera')).toStrictEqual('Los Hermanos Sean Unidos Porque Ésa Es La Ley Primera')
	})
	test('normalize', () => {
		expect(h3lp.string.normalize('abcdefghijklmnopqrstuvwxyz')).toStrictEqual('abcdefghijklmnopqrstuvwxyz')
		expect(h3lp.string.normalize('0123456789')).toStrictEqual('0123456789')
		expect(h3lp.string.normalize('ABCDEFGHIJKLMNOPQRSTUVWXYZ')).toStrictEqual('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
		expect(h3lp.string.normalize('Ø ø')).toStrictEqual('00')
		expect(h3lp.string.normalize('À Á Â Ã Ä Å à á â ã ä å Ā ā Ă ă Ą ą Ƌ ƌ Ǎ ǎ Ȁ ȁ Ȃ ȃ Ȧ ȧ')).toStrictEqual('AAAAAAaaaaaaAaAaAaaaAaAaAaAa')
		expect(h3lp.string.normalize('ƀ Ɓ Ƃ ƃ')).toStrictEqual('bbbb')
		expect(h3lp.string.normalize('Ç ç Ć ć Ĉ ĉ Ċ ċ Č č Ɔ Ƈ ƈ')).toStrictEqual('CcCcCcCcCcCCc')
		expect(h3lp.string.normalize('Ď ď Đ đ  Ɖ Ɗ ȡ')).toStrictEqual('DdDdDDd')
		expect(h3lp.string.normalize('È É Ê Ëè é ê ë Ē ē Ĕ ĕ Ė ė Ę ę Ě ě  Œ œ Ǝ Ɛ ǝ Ȅ ȅ Ȇ ȇ Ȩ ȩ')).toStrictEqual('EEEEeeeeEeEeEeEeEeEeEEeEeEeEe')
		expect(h3lp.string.normalize('Ƒ ƒ')).toStrictEqual('Ff')
		expect(h3lp.string.normalize('Ì Í Î Ïì í î ï')).toStrictEqual('IIIIiiii')
		expect(h3lp.string.normalize('Ĝ ĝ Ğ ğ Ġ ġ Ģ ģ Ɠ Ǥ ǥ Ǧ ǧ Ǵ ǵ')).toStrictEqual('GgGgGgGgGGgGgGg')
		expect(h3lp.string.normalize('Ĥ ĥ Ħ ħ Ȟ ȟ')).toStrictEqual('HhHhHh')
		expect(h3lp.string.normalize('Ĩ ĩ Ī ī Ĭ ĭ Į į İ Ɨ Ǐ ǐ Ȉ ȉ Ȋ ȋ')).toStrictEqual('IiIiIiIiIIIiIiIi')
		expect(h3lp.string.normalize('Ĵ ĵ')).toStrictEqual('JJ')
		expect(h3lp.string.normalize('Ƙ ƙ Ǩ ǩ')).toStrictEqual('KkKk')
		expect(h3lp.string.normalize('Ĺ ĺ Ļ ļ Ľ ľ Ŀ ŀ Ł ł ƚ')).toStrictEqual('LlLlLlLlLll')
		expect(h3lp.string.normalize('Ñ ñ Ń ń Ņ ņ Ň ň Ɲ ƞ  Ǹ ǹ Ƞ')).toStrictEqual('NnNnNnNnNnNnN')
		expect(h3lp.string.normalize('Ò Ó Ô Õ Ö ò ó ô õ ö Ō ō Ŏ ŏ Ő ő Ɵ Ơ ơ Ǒ ǒ Ȍ ȍ Ȏ ȏ Ȯ ȯ')).toStrictEqual('OOOOOoooooOoOoOoOOoOoOoOoOo')
		expect(h3lp.string.normalize('Ƥ ƥ')).toStrictEqual('Pp')
		expect(h3lp.string.normalize('Ǫ ǫ')).toStrictEqual('QQ')
		expect(h3lp.string.normalize('Ŕ ŕ Ŗ ŗ Ř ř Ʀ Ȑ ȑ Ȓ ȓ')).toStrictEqual('RrRrRrRRrRr')
		expect(h3lp.string.normalize('Ś ś Ŝ ŝ Ş ş Š š Ș ș')).toStrictEqual('SsSsSsSsSs')
		expect(h3lp.string.normalize('Ţ ţ Ť ť Ŧ ŧ ƫ Ƭ ƭ Ʈ Ț ț')).toStrictEqual('TtTtTttTtTT')
		expect(h3lp.string.normalize('Ù Ú Û Ü ù ú û ü Ũ ũ Ū ū Ŭ ŭ Ů ů Ű ű Ư ư Ʋ Ǔ ǔ Ȕ ȕ Ȗ ȗ')).toStrictEqual('UUUUuuuuUuUuUuUuUuUuuUuUuUu')
		expect(h3lp.string.normalize('Ý ý ÿ Ų ų')).toStrictEqual('YyyYy')
		expect(h3lp.string.normalize('Ŵ ŵ')).toStrictEqual('Ww')
		expect(h3lp.string.normalize(' Ŷ ŷ Ÿ Ȳ ȳ')).toStrictEqual('YyYYy')
		expect(h3lp.string.normalize('Ɯ')).toStrictEqual('W')
		expect(h3lp.string.normalize('Ƴ ƴ')).toStrictEqual('yy')
		expect(h3lp.string.normalize('Ź ź Ż ż Ž ž Ƶ ƶ Ȥ ȥ')).toStrictEqual('ZzZzZzZzZz')
	})
})
